[package]
name = "pf2e-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }
thiserror = "1.0.37"


[features]
default = ["serde"]
serde = []